### ISSUE TITLE
add Hang as code manager

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-ncio#20]
@Hang-Lei-NOAA please add yourself as a code manager for this repo. (That is, add your name in the README.)

Do you have admin permissions for this repo?

**Comment by edwardhartnett** [comment]
@Hang-Lei-NOAA can we get this done?

**Comment by Hang-Lei-NOAA** [comment]
Sure!

**Comment by Hang-Lei-NOAA** [comment]
I have changed the name of the code manager.

**Comment by edwardhartnett** [comment]
OK, I just wanted to add you, not change to you. ;-)

We are going to go with 2 code managers for repos. It will take us a while to assign 2 to all the repos, but we'll have 2 for this one, you and me. ;-)

**Comment by Hang-Lei-NOAA** [comment]
Ok, I changed back.
The old consideration is to clear responsibility. that is why only one
manager is set for each repo.

**Comment by edwardhartnett** [comment]
One person is not enough though. ;-) I take long vacations, you should be able to as well. So we need someone to cover.

Now what happens if we are both on a long vacation? ;-) Well, no system is perfect. But two heads are better than one.

But you can put your name first, because I am going to be digging into UFS_UTILS, so much as I would enjoy writing more tests for this repo, that will fall to you in the short term. ;-)
