### ISSUE TITLE
Turn on branch protections for develop branch

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-ncio#22]
@Hang-Lei-NOAA you should not have been able to change the README without a PR and without a review. ;-)

So can you change permissions on this repo so that:
* develop branch is protected
* pull requests are always required
* these rules apply to admins
* CI tests must pass

Let me know if you need help with these settings, they can be a bit tricky. But they should be the same on all NCEPLIBS.

**Comment by Hang-Lei-NOAA** [comment]
Okay,  I will set it soon.

**Comment by Hang-Lei-NOAA** [comment]
The protection has been  added to develop branch
