### ISSUE TITLE
why do 5d read_vardata functions have less parameters?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-ncio#28]
@jswhit here's a question about the ncio library code.

There are a bunch of functions like this:
```
  interface read_vardata
     module procedure read_vardata_1d_r4, read_vardata_2d_r4, read_vardata_3d_r4,&
          read_vardata_4d_r4, read_vardata_5d_r4, &
          read_vardata_1d_r8, read_vardata_2d_r8, read_vardata_3d_r8,&
          read_vardata_4d_r8, read_vardata_5d_r8, &
          read_vardata_1d_int, read_vardata_2d_int, &
          read_vardata_3d_int, read_vardata_4d_int, read_vardata_5d_int, &
          read_vardata_1d_short, read_vardata_2d_short, &
          read_vardata_3d_short, read_vardata_4d_short, read_vardata_5d_short , &
          read_vardata_1d_byte, read_vardata_2d_byte, &
          read_vardata_3d_byte, read_vardata_4d_byte, read_vardata_5d_byte, &
          read_vardata_1d_char, read_vardata_2d_char, &
          read_vardata_3d_char, read_vardata_4d_char, read_vardata_5d_char
  end interface read_vardata

```

All these functions except the 5d ones have 8 parameters:

```
  subroutine read_vardata_1d_r4(dset, varname, values, nslice, slicedim, ncstart, nccount, errcode)
    real(4), allocatable, dimension(:), intent(inout) :: values
    include "read_vardata_code_1d.f90"
  end subroutine read_vardata_1d_r4

```

But the 5d functions do not include the slice and start/count parameters:

```
  !> @copydoc read_vardata_4param
  subroutine read_vardata_5d_byte(dset, varname, values, errcode)
    integer(1), allocatable, dimension(:,:,:,:,:), intent(inout) :: values
    include "read_vardata_code_5d.f90"
  end subroutine read_vardata_5d_byte

```

How come the 5D vars don't get these parameters?

**Comment by jswhit** [comment]
Looks like a bug.  @CoryMartin-NOAA - do you remember why you didn't add this to read_vardata_5d?

**Comment by CoryMartin-NOAA** [comment]
I don't remember unfortunately, most likely explanation is I didn't need it at the time (we were scrambling to get all of this parallel netCDF working) and it slipped through the cracks.  I agree this is likely a bug/oversight and needs fixed.

**Comment by edwardhartnett** [comment]
Can you fix please? And also add a test for it?

Make sure you get the latest develop branch, I changed the doxygen...

**Comment by CoryMartin-NOAA** [comment]
@edwardhartnett sure, give me a few days and I think I can do that.

**Comment by CoryMartin-NOAA** [comment]
So the reason why this was never done before is because it really only is usable for 6D variables when you select a subset to pull a 5D array out of it. The sample netCDF file only has 4D vars. Do we want a second sample file added that is just one 6D var? or add something synthetic to this sample FV3 history file?
Code changes I've done so far are here: https://github.com/CoryMartin-NOAA/NCEPLIBS-ncio/tree/bugfix/5dvar

**Comment by edwardhartnett** [comment]
Instead, write a test which creates a file with a 6D var, using ncio, and then read it.

**Comment by CoryMartin-NOAA** [comment]
I'm not sure that's doable with this current library (it's very simple) and it needs an input template dataset. I don't think you can create new variables using it. I could create the file using nf90 calls and then read it using ncio, but that seems less than desirable.

**Comment by edwardhartnett** [comment]
I would use the netCDF functions to create the file and the ncio functions to read it. That's perfectly fine.

I think it's also fine to create a file with ncio and use netCDF functions to ensure it was created correctly.

In general it's easier to deal with test data that is constructed, than to put data files into the repo, or find some other way of getting them.

**Comment by jswhit** [comment]
Or we just change the docs to say that only 5d vars are supported.  If we allow 6d vars, then we need a read_vardata_6d and we will have the same problem

**Comment by CoryMartin-NOAA** [comment]
@edwardhartnett ok then I'll create a dummy 6D dataset, and read 5D from it to test this functionality.

**Comment by CoryMartin-NOAA** [comment]
@jswhit this might be the preferred solution. Can you think of a use case where we would have 6 dimensions? Even 5 seems to be fairly rare (ensemble members?) and we already support slicing a 5D variable into a 4D array.

**Comment by jswhit** [comment]
Yes, I think 5 is probably the most we would ever use (ens_size,time,z,y,x)

**Comment by CoryMartin-NOAA** [comment]
Then in that case, definitely just change the documentation (where is 5D/6D defined?). I think the confusion comes from the names of the separate .f90 files. read_vardata_code_4d.f90 reads either a 4D array completely from a 4D variable, or a 4D slice from a 5D variable (if you specify which dim/index you want). So if we only support 5D arrays max, that's why the read_vardata_code_5d call doesn't feature the optional arguments like the others do.

**Comment by edwardhartnett** [comment]
Well this all started with a question about whether those args are needed. So if they are not, that's fine, and the documentation currently reflects that. I will add an explanation of why.

But you are still going to add a test for them, correct? Every function must be tested, as a bare minimum of testing...

**Comment by CoryMartin-NOAA** [comment]
Ok so I guess the ideal situation is create using nf90, a 1D, 2D, 3D, 4D, 5D variable each, then read each in its entirety and then read slices from each? I guess my bigger question is how much effort to put into adding testing to this library, I'm not sure it will be used much beyond GSI and the enkf_chgres_recenter utility, both of which will probably not be in use in a few years.

**Comment by jswhit** [comment]
I think the current test covers at least 1d,3d and 4d by reading GFS history files.  Depends on what you mean by 'every function tested' - the read_vardata interface is tested, but not every possible dimension/variable type allowed is tested.

**Comment by edwardhartnett** [comment]
What I mean by 'every function tested' is actually pretty straightforward. ;-) It's also the bare minimum. There is also testing for the different variations of parameters.

I have added test coverage analysis for this code. It is poorly tested at the moment. However it will not be much work to fill in the gaps and properly test all the code.

Full testing is required for all NCEPLIBS/UFS_UTILS code.

**Comment by edwardhartnett** [comment]
@CoryMartin-NOAA to address your questions:
* Full testing would still be required if this library was only going to support utilities that are going to be operational for several years.
* Isn't this code also used in fv3atm?
* There is some hope to use this library more generally within EMC. 

Full testing is normal in science libraries that we use and depend on. Is there some reason we want to release untested code?

**Comment by jswhit** [comment]
it is not used by the UFS model, just by the GSI and associated utilities.

**Comment by edwardhartnett** [comment]
OK, I have documented the different signatures for the 5D functions. We just need some tests and I will close this issue...

**Comment by edwardhartnett** [comment]
I will add another issue for the 5D tests, and close this issue.
