### ISSUE TITLE
need tests for quantization code

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-ncio#32]
Test coverage says that the quantization code is not used in any tests. If this is true, it needs to be tested.

**Comment by edwardhartnett** [comment]
Well that was quick. ;-)

Here's a snapshot of current code coverage.

![image](https://user-images.githubusercontent.com/38856240/114756374-e82cf080-9d17-11eb-8548-2bca494aa749.png)

I have merged these changes to this PR, so soon we can see the new code coverage...

**Comment by edwardhartnett** [comment]
@CoryMartin-NOAA you can download the code coverage report by opening the "Details" on the build called "Build in source and do code coverage anaysis / build"

Once you open that build, there is an "Artifacts" menu on the upper-right. Under it is one item, a zip file. Download it, unzip it, and then open test-coverage.html to get the top-level report. Click on the filenames to drill down to a line-by-line analysis of what code was run.

We want 100% if we can get it, but often we can't, if we are properly error checking. However, get as close as you can.

In the current PR, what you are not testing is what happens if nbits is <=0 or >= 32. This should be tested.

**Comment by CoryMartin-NOAA** [comment]
Added a second test when nbits is 32.
