### ISSUE TITLE
Identify in the docs where this library is used...

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-ncio#34]
You say that this library is used in the GSI and some utilities.

By GSI do you mean this: https://dtcenter.ucar.edu/com-GSI/users/docs/?

What utilities do you mean? Can you be specific?

**Comment by CoryMartin-NOAA** [comment]
GSI here: https://github.com/NOAA-EMC/GSI/tree/master/src/fv3gfs_ncio has an older version of this library (the library was designed to simplify reading for GSI), in the future we can link to using NCEPLIBS-ncio. This library is used to read the GFS forecast files for use in data assimilation.

The only other tool I know of that uses it is this:
https://github.com/NOAA-EMC/global-workflow/tree/develop/sorc/enkf_chgres_recenter_nc.fd
enkf_chgres_recenter_nc will read in a template output file, an input file, and regrid the input file to the template output file resolution.

**Comment by edwardhartnett** [comment]
Thanks, I have added that info to the README...
