### ISSUE TITLE
test for parallel I/O file creates/opens

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-ncio#44]
All testing is sequential. We need parallel I/O tests too.

**Comment by edwardhartnett** [comment]
One part of parallel I/O tests is to grab a copy of of this file from UFS_UTILS and put it in the cmake directory of this project:
https://github.com/NOAA-EMC/UFS_UTILS/blob/develop/cmake/LibMPI.cmake

Then you write an MPI program that runs on 4 processors and tests the ncio library. Here's an MPI test so you see what it looks like:
https://github.com/NOAA-EMC/UFS_UTILS/blob/develop/tests/chgres_cube/ftst_program_setup.F90

**Comment by arunchawla-NOAA** [comment]
What is the status of this? There is a PR for it ?

**Comment by BrianCurtis-NOAA** [comment]
@arunchawla-NOAA it does have a PR linked already. The PR works except for MacOS and we are trying to figure it out.
