### ISSUE TITLE
We should test for a specific version of parallel I/O netCDF (4.7.4), and that must be installed in GitHub CI

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-ncio#45]
We should test for a specific version of netCDF

**Comment by BrianCurtis-NOAA** [comment]
CMake can force a specific version at build, so we can add that there (maybe it is already but need to be updated?). I have not worked with Github CI yet, so any guidance would be helpful. I'll see what I can learn hands on.

**Comment by edwardhartnett** [comment]
I just updated this issue to cover the work already done in your open PR. When you merge that, you can close this issue too.

Alternatively, you can submit a new PR, with the changes to the github workflow and CMake file currently in your open PR, and use that to close this issue. Then circle around to your test problem again, with these changes already in the develop branch.

Sometimes when doing PRs we encounter other problems, such as this one, which can be usefully solved on their own. In that case, it's good to use a separate issue and PR to solve those sub-problems, and then take up the main task again, with some of the underbrush cleared away.

This allows us to make progress without having all the answers. As we develop some useful changes, we can get those merged, and then circle around to the unsolved problem once again. With these answers in place, the unsolved problem is then smaller and more amenable to solution.

**Comment by BrianCurtis-NOAA** [comment]
This was taken care of in #50 closing.
