### ISSUE TITLE
rename module module_fv3gfs_ncio to just module_ncio.

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/NCEPLIBS-ncio#5]
This module is generic to netCDF and not specific to FV3GFS.
There is no requirement that this library to be tied to the FV3GFS.  It provides generic user friendly interfaces to netCDF Fortran API similar to netcdf4-python.

**Comment by edwardhartnett** [comment]
@aerorahul are you going to do this? If not, who is? If so, please assign the issue to yourself.

**Comment by aerorahul** [comment]
@edwardhartnett 
Sure I can do that.
I will have to make sure to coordinate this with the GSI.
@jswhit2 Do you see obvious reasons why this cannot be made into a generic netCDF IO api?

**Comment by jswhit** [comment]
It's never going to be entirely generic - it really only supports the classic data model and variables up to 4d (maybe 5d?).  It's certainly not specific to fv3gfs though.

**Comment by aerorahul** [comment]
Thanks @jswhit for the comment.
Do you agree, for the applications in the UFS, this library would be usable wherever a classic data model and variables are used.
If not, there is no point in doing any of the work in this issue.

**Comment by jswhit** [comment]
yes, I agree.  Shall I go ahead and change the name in PR #16?

**Comment by jswhit** [comment]
Done

**Comment by aerorahul** [comment]
fixed in #16
