### ISSUE TITLE
Create 1.1.1 or 1.2.0 release for time_iso variable addition and fix for issue #58

### ISSUE THREAD

**Issue by MichaelLueken** [NOAA-EMC/NCEPLIBS-ncio#60]
@kgerheiser @Hang-Lei-NOAA Would it be possible to create a new 1.1.1 or 1.2.0 release for NCEPLIBS-ncio and have this version propagated through the stack?  While the update in ncio/1.1.0 does correct issues encountered in getsfcensmeanp, it leads to failures in the GSI itself.  The latest update, [ac37269](https://github.com/NOAA-EMC/NCEPLIBS-ncio/commit/ac37269f8e727c8470b123cf08b674613afa991b), contains changes that will allow the GSI to run without issue.

I would be greatly appreciative if you could create a new release from this version and build it in the stack on the various machines.

Thank you very much for your time.

**Comment by kgerheiser** [comment]
Yes, I will take care of this.

**Comment by MichaelLueken** [comment]
This tag has been created, so I am closing this issue.
