### ISSUE TITLE
Create 1.1.2 release for time_iso variable addition and fixes to both read_vardata_code_1d and write_vardata_code

### ISSUE THREAD

**Issue by MichaelLueken** [NOAA-EMC/NCEPLIBS-ncio#64]
@kgerheiser @Hang-Lei-NOAA @edwardhartnett Would it be possible to create a new 1.1.1 or 1.1.2 release for NCEPLIBS-ncio and have this version propagated through the stack? While the update in ncio/1.1.1 does correct issues encountered in getsfcensmeanp, as well as corrects issues while dealing with the increment, it leads to failures in the analysis due to write_varadata_code. The latest update, [95a0d9b](https://github.com/NOAA-EMC/NCEPLIBS-ncio/commit/95a0d9b56c11bcfb76c9093e13383d3b28cfc462), contains changes that will allow the GSI to run in full analysis mode without issue.

I would be greatly appreciative if you could create a new release from this version and build it in the stack on the various machines.

Thank you very much for your time.

**Comment by Hang-Lei-NOAA** [comment]
We will do it soon.

**Comment by Hang-Lei-NOAA** [comment]
@MichaelLueken-NOAA Are you sure that this fix has solved all the issues?

**Comment by MichaelLueken** [comment]
@Hang-Lei-NOAA I have applied the change to my stack built ncio library and was able to test both the increment mode (the read_vardata_code_1d fix) and full analysis mode (the write_vardata_code fix) and both behaved as expected.  All issues, that I'm aware of, should now be corrected.

**Comment by Hang-Lei-NOAA** [comment]
@Michael Lueken - NOAA Affiliate ***@***.***> Thanks Michael!

**Comment by MichaelLueken** [comment]
@Hang-Lei-NOAA Thank you very much for creating the v1.1.2 tag!  I will update the existing hpc-stack issue ([#462](https://github.com/NOAA-EMC/hpc-stack/issues/462)) for the installation of this version of the library on the various machines.  I will also close this issue now.
