### ISSUE TITLE
Empty test coverage results

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [NOAA-EMC/NCEPLIBS-ncio#78]
The current test coverage output is empty even though the CI doesn't fail anymore. I can resolve the issue by removing the `-fprofile-abs-path` from CMAKE_Fortran_FLAGS and copying the source files into build/src/CMakeFiles/ncio.dir/, but I still don't know what the issue is.

**Comment by AlexanderRichert-NOAA** [comment]
@edwardhartnett for what it's worth, I just checked the rest of NCEPLIBS and none of them have this problem, i.e., their test coverage outputs all appear to be correctly populated. I suspect it's some combination of how the source files get built (i.e., "included" as opposed to compiled directly) and how they're handled by cmake.

**Comment by edwardhartnett** [comment]
Probably you are right. I hate the way the code is organized in this repo. It's nutty!

Can you submit a PR with your hack?
