### ISSUE TITLE
Add doxygen documentation

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-ncio#8]
As described here: https://github.com/NOAA-EMC/NCEPLIBS/issues/121

**Comment by edwardhartnett** [comment]
@Hang-Lei-NOAA can I get some help with the doxygen in NCEPLIBS-ncio?

I foolishly did not require doxygen before we took this code, which is a mistake I will not make again. ;-)

Can you review the outstanding PR, and then I will merge it. Then , if you could submit another PR with the rest of the doxygen changes, we can get a release out this week.

**Comment by Hang-Lei-NOAA** [comment]
Sure, no problem.

**Comment by edwardhartnett** [comment]
@Hang-Lei-NOAA any progress? I would like to see this complete today so we can release...

**Comment by edwardhartnett** [comment]
@Hang-Lei-NOAA any progress? It would be best to get this done early this week...

**Comment by Hang-Lei-NOAA** [comment]
I saw that you have added basic information for doxygen in the repo. My
work is to fulfill more detailed information to that. I have started to add
some. Will continue to add after installation of hpc stack on xsede
machine. Plan to finish by Thursday.
